AUDIO_OUTPUT_ANALOG = 0
AUDIO_OUTPUT_DIGITAL = 1

KEY_DOWN_ARROW = '\x1B[B'
KEY_LEFT_ARROW = '\x1B[D'
KEY_PAGE_DOWN = '\x1B[6~'
KEY_PAGE_UP = '\x1B[5~'
KEY_RIGHT_ARROW = '\x1B[C'
KEY_UP_ARROW = '\x1B[A'
